# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    platform.entity.user.class: AppBundle\Entity\User

services:
    platform.user.repository:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User
    platform.user.provider:
        class: AppBundle\Provider\UserProvider
        arguments: ["@platform.user.repository"]